### ISSUE TITLE
デザイン修正

### ISSUE THREAD

**Issue by kkiriyama** [sota-ma/soma#121]
- columns, mypageのカラムの幅設定
- /にアクセスするとarticlesに飛ぶように
- about画面のスマホ表示

**Comment by teiflower** [comment]
>/にアクセスするとarticlesに飛ぶように
に関して、エラーが発生した時にhomeに飛ぶやつも合わせて修正お願いします

**Comment by teiflower** [comment]
できてなかったらしい

**Comment by teiflower** [comment]
component/card　に
`.card {
  margin: 5px;
  cursor: pointer;
  max-width: 300px;
}`
が適用されているのに、なんで過剰に横幅が長くなってしまうんだろう…

**Comment by kkiriyama** [comment]
トップページへのアクセスをarticles画面にリダイレクトするの、ちょっと難しいです.......(普通にリダイレクトするとローディング画面で今のトップページが見えちゃう)

**Comment by teiflower** [comment]
そもそもトップがちゃんとしてないことに対する応急措置だったとおもうので、文字サイズが改善されたなら不要だと思います。
