### ISSUE TITLE
記事一覧の検索バーがごちゃごちゃしているのを直す

### ISSUE THREAD

**Issue by teiflower** [sota-ma/soma#129]
要素が増えたらごちゃごちゃしてきたのでなんとかする
スマホ表示も整える

**Comment by teiflower** [comment]
ごちゃごちゃしているあたりの階層を整理すると

診療科で検索
　┗入力フィールド
　┗検索ボタン
キーワードで検索
　┗カテゴリ選択
　┗入力フィールド
　┗検索ボタン
　┗リセットボタン
記事ソートボタン

-----
問題点
・記事ソートボタンが検索バーの仲間のように表示されていてわかりにくい。
・診療科で検索は明示されているが、キーワード検索はそれであることが記載されていない。
・同じ「検索」であるにも関わらず、入力欄が個別に用意されている。
・入力フィールドに付随するものが並列ではない。
・検索ワードを入力するだけではなく、カテゴリ選択までしなければならない。
・リセットボタン、必要？？？？？？？必要だったとして、入力フィールドのなかにばってん表示するやつでよくない？

**Comment by kkiriyama** [comment]
・記事ソートボタンが検索バーの仲間のように表示されていてわかりにくい。→なるほど具体的にどのような改善案がありますか
・診療科で検索は明示されているが、キーワード検索はそれであることが記載されていない。→統一しましょう
・同じ「検索」であるにも関わらず、入力欄が個別に用意されている。→これは統一するのはちょっと難しいと思う.....(UIの観点でどのような例を考えているのか教えてもらえると嬉しい)
・入力フィールドに付随するものが並列ではない。→よくわからないのでもう少し詳しくお願いします
・検索ワードを入力するだけではなく、カテゴリ選択までしなければならない。→わかる全部一括でよくない？と思ったり
・リセットボタン、必要？？？？？？？必要だったとして、入力フィールドのなかにばってん表示するやつでよくない？→これももっともな話で、そのように修正しましょう

**Comment by teiflower** [comment]
>・記事ソートボタンが検索バーの仲間のように表示されていてわかりにくい。→なるほど具体的にどのような改善案がありますか
デザインで違うもののように見せる。揃え方や色で区別できると思う。

>・診療科で検索は明示されているが、キーワード検索はそれであることが記載されていない。→統一しましょう
します

>・同じ「検索」であるにも関わらず、入力欄が個別に用意されている。→これは統一するのはちょっと難しいと思う.....(UIの観点でどのような例を考えているのか教えてもらえると嬉しい)
>・検索ワードを入力するだけではなく、カテゴリ選択までしなければならない。→わかる全部一括でよくない？と思ったり
カテゴリ選択をせずに一括ですむようにするなら、キーワード・診療科も含めて一括でいいのでは？というふうに思っています。

>・入力フィールドに付随するものが並列ではない。→よくわからないのでもう少し詳しくお願いします
カテゴリ選択欄とリセットボタンがキーワード検索にのみある、ということです。他の項目とかぶってましたね…

>・リセットボタン、必要？？？？？？？必要だったとして、入力フィールドのなかにばってん表示するやつでよくない？→これももっともな話で、そのように修正しましょう
（もし統一しないなら）診療科の検索の方にも同じボタンをください

**Comment by teiflower** [comment]
デザイン部分はおわった (#139) ので実装お願いします

・文字列で検索する検索からカテゴリ選択をなくす
・文字列で検索する検索からResetボタンをなくす（or入力フィールドの中に入れる）
・（入力フィールドの中に入れるなら診療科名のほうにも消去ボタンを入れる。）
