### ISSUE TITLE
関連する診療科、データセットの特性による分類

### ISSUE THREAD

**Issue by kkiriyama** [sota-ma/soma#27]
データセットのavailabilityと関連する診療科でタグ分類をしたい

**Comment by Lenqth** [comment]
datasetってtagとはまた違う役割なんですかね？

**Comment by kkiriyama** [comment]
tagはキーワード群なのて性質が違います

**Comment by kkiriyama** [comment]
えーと、contentfulのtagは論文中のキーワード群をさしていて、ここでのタグはrelated-departmentとdataset-hogehogeをさしています（ややこしくてすみません）

**Comment by Lenqth** [comment]
なるほど項目はcontent modelの方で設定可能なんですね。

**Comment by Lenqth** [comment]
あとはフィルターしたいならSNSのでユーザーごとのTL出したのと同じ感じでできそうですよね。

**Comment by Lenqth** [comment]
(contentfulだからちょっと違うか)

**Comment by kkiriyama** [comment]
APIがどういうクエリを受けるかに結構依存する気がする

**Comment by Lenqth** [comment]
試してみる。
