### ISSUE TITLE
vueのstyleをできるだけscopedにする

### ISSUE THREAD

**Issue by Lenqth** [sota-ma/soma#28]
`<style scoped>`
https://vue-loader-v14.vuejs.org/ja/features/scoped-css.html

scopedにすることで
・そうでないものよりも優先度が上がる
・よそにstyleの影響が漏れない
などのメリットがあるので、できるだけstyleはscopedにすることを提案します。

**Comment by Lenqth** [comment]
これで悪影響が出ないかって用意に調べられるかな…

**Comment by akihiro-iwata** [comment]
#69
