### ISSUE TITLE
CONTENT TYPEがarticleのもののみ表示する

### ISSUE THREAD

**Issue by Lenqth** [sota-ma/soma#29]
writerを追加したことにより、
![image](https://user-images.githubusercontent.com/4355315/57966442-e2dc9500-798c-11e9-950e-7a33d7c53bf7.png)
こんなのが出てきてしまったので直します

**Comment by Lenqth** [comment]
writerのページとか作る？

**Comment by kkiriyama** [comment]
作ってもいいとは思っている
