### ISSUE TITLE
ログイン等でのalertを吹き出し等にする

### ISSUE THREAD

**Issue by Lenqth** [sota-ma/soma#38]

**Comment by Lenqth** [comment]
![image](https://user-images.githubusercontent.com/4355315/57998919-738eae80-7b0e-11e9-86d6-a1868ecdd1c7.png)

**Comment by Lenqth** [comment]
待ってください、まだログイン画面とパスワード再発行画面が残ってます…

**Comment by akihiro-iwata** [comment]
# パスワードリセット
![スクリーンショット 2019-06-26 18 18 33](https://user-images.githubusercontent.com/8016453/60167826-d4608380-983e-11e9-8fcd-a8373ab41691.png)

# ログイン
![スクリーンショット 2019-06-26 18 18 04](https://user-images.githubusercontent.com/8016453/60167832-d88ca100-983e-11e9-992b-7d6b11f9b371.png)
![スクリーンショット 2019-06-26 18 18 19](https://user-images.githubusercontent.com/8016453/60167833-d9253780-983e-11e9-81e8-d297d767bb5b.png)
