### ISSUE TITLE
articleページ　カードデザイン変更

### ISSUE THREAD

**Issue by teiflower** [sota-ma/soma#61]
ヘッダー・フッターが意味をなしてないので無くす。
論文タイトルの長さの文字列は中央揃えだと読みにくい、左揃えに。
情報を整理する。
記事作成者名を追加する。
articleページとdetailページで「投稿」の指す意味が違うのを修正する。

**Comment by teiflower** [comment]
詳細へ飛ぶのを、ボタンじゃなくてカード全体に適用できませんかね
@kkiriyama @akihiro-iwata

**Comment by urc-pen** [comment]
できますよ！

**Comment by teiflower** [comment]
13日以降になると思いますが、カードのレイアウト整えたあとにお願いします！

**Comment by urc-pen** [comment]
はい！
