### ISSUE TITLE
article detailページ　情報のレイアウト変更

### ISSUE THREAD

**Issue by teiflower** [sota-ma/soma#63]
タイトルをとりあえず囲むのをやめる。
タイトルをタイトルだとわかるようデザインを変更する。
keyword, related department のボタンを改善する。
トップ右上に記事の作成者名と作成日を右寄せで入れる
要旨に関して、ウィンドウの幅を狭くした時に原文と日本語訳が横並びから縦並びになる閾値が小さすぎるので大きくする。

---ここからは必要かどうか不明---
keyword, related departmentと並列する形でdatasetが手に入るかどうか、の項目を作る（？）
データセットの表に含める項目を「指標」「スコア」のみにする。データセットの内容（出典）と入手の可否は表の説明文のように付け加える

**Comment by teiflower** [comment]
articleページとdetailページで「投稿」の指す意味が違うのを統一する

**Comment by teiflower** [comment]
badgeの中の文字とバッジの外枠の横軸が揃わないことが修正できなくて困った

**Comment by kkiriyama** [comment]
Bootstrapのバッジを必ずしも使う必要はないのでは（CSSで同様のものを書くことは可能）

**Comment by teiflower** [comment]
なるほど
将来的にはこのバッジをクリックすると検索ができる仕様になるのかと思って、それにはバッジの方が都合がいいのかと思ってたけどそういうことではない？
