### ISSUE TITLE
article detail画面に必要な情報を追加

### ISSUE THREAD

**Issue by kkiriyama** [sota-ma/soma#72]
作成者、査読者情報などを載せる、デザインは後回し

**Comment by teiflower** [comment]
・作成者情報
・データセットの有無
は #73 で枠を作ってあります。

また、article画面のカードにも記事の作成者情報を載せる欄があります。

**Comment by teiflower** [comment]
figureを載せられるようにできるといいねぇ

**Comment by kkiriyama** [comment]
作成者情報がhogeになっているので作成者を入れる
