### ISSUE TITLE
マイページにアクセスするとエラー

### ISSUE THREAD

**Issue by kkiriyama** [sota-ma/soma#98]
`Failed to get document because the client is offline.`
となる

**Comment by akihiro-iwata** [comment]
これ多分functions配下のindexでルーティング指定されてないからですね。コラム画面のリロードエラーと同じような話だと思われます。

**Comment by kkiriyama** [comment]
なるほどですね（そういえばfunctionsのindex長らくいじってなかった）

**Comment by akihiro-iwata** [comment]
ページ足すたびにあれ修正しないといけないのだるいっていうか、これこそテストコードで保護したいですね

**Comment by akihiro-iwata** [comment]
あれ、まだ解消しない・・・

**Comment by kkiriyama** [comment]
まだデプロイしてないです

**Comment by akihiro-iwata** [comment]
あ、なるほど

**Comment by akihiro-iwata** [comment]
#109
